package com.rasik.model;

// Generated Jan 20, 2014 10:30:33 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.codehaus.jackson.annotate.JsonBackReference;
import org.hibernate.annotations.NamedQueries;
import org.hibernate.annotations.NamedQuery;

/**
 * Awarddetail generated by hbm2java
 */
@Entity
@Table(name = "awarddetail", catalog = "rasiknew")
@NamedQueries(
{@NamedQuery(name="findAllAwardDetails",query="from Awarddetail "),
@NamedQuery(name="findAwardByName",query="from Awarddetail it where it.awardDetailsEnglish = :awardDetailsEnglish")
})

public class Awarddetail implements java.io.Serializable {

	private Integer awardDetailId;
	@JsonBackReference
	private Set<Items> items;
	private String awardDetailsEnglish;
	private Date dateOfAward;
	private String awardDetailsMarathi;

	public Awarddetail() {
	}

	
	public Awarddetail(Set<Items> items, String awardDetailsEnglish,
			Date dateOfAward, String awardDetailsMarathi) {
		this.items = items;
		this.awardDetailsEnglish = awardDetailsEnglish;
		this.dateOfAward = dateOfAward;
		this.awardDetailsMarathi = awardDetailsMarathi;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "AwardDetailId", unique = true, nullable = false)
	public Integer getAwardDetailId() {
		return this.awardDetailId;
	}

	public void setAwardDetailId(Integer awardDetailId) {
		this.awardDetailId = awardDetailId;
	}

	@ManyToMany(fetch = FetchType.EAGER,mappedBy="awarddetails")
	public Set<Items> getItems() {
		return this.items;
	}

	public void setItems(Set<Items> items) {
		this.items = items;
	}

	@Column(name = "AwardDetailsEnglish", length = 240)
	public String getAwardDetailsEnglish() {
		return this.awardDetailsEnglish;
	}

	public void setAwardDetailsEnglish(String awardDetailsEnglish) {
		this.awardDetailsEnglish = awardDetailsEnglish;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DateOfAward", length = 10)
	public Date getDateOfAward() {
		return this.dateOfAward;
	}

	public void setDateOfAward(Date dateOfAward) {
		this.dateOfAward = dateOfAward;
	}

	@Column(name = "AwardDetailsMarathi", length = 345)
	public String getAwardDetailsMarathi() {
		return this.awardDetailsMarathi;
	}

	public void setAwardDetailsMarathi(String awardDetailsMarathi) {
		this.awardDetailsMarathi = awardDetailsMarathi;
	}

}
