package com.rasik.model;

// Generated Jan 20, 2014 10:30:33 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonBackReference;
import org.hibernate.annotations.NamedQueries;
import org.hibernate.annotations.NamedQuery;

/**
 * Bindingtype generated by hbm2java
 */
@Entity
@Table(name = "bindingtype", catalog = "rasiknew")
@NamedQueries({
@NamedQuery(name="findAllBindingtypes",query="from Bindingtype "),
@NamedQuery(name="findBindingTypeByName",query="from Bindingtype it where it.bindingTypeName = :bindingTypeName")
})
public class Bindingtype implements java.io.Serializable {

	private Integer bindingTypeId;
	private String bindingTypeName;
	@JsonBackReference
	private Set<Items> itemses = new HashSet<Items>(0);

	public Bindingtype() {
	}

	public Bindingtype(String bindingTypeName, Set<Items> itemses) {
		this.bindingTypeName = bindingTypeName;
		this.itemses = itemses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "BindingTypeId", unique = true, nullable = false)
	public Integer getBindingTypeId() {
		return this.bindingTypeId;
	}

	public void setBindingTypeId(Integer bindingTypeId) {
		this.bindingTypeId = bindingTypeId;
	}

	@Column(name = "BindingTypeName", length = 30)
	public String getBindingTypeName() {
		return this.bindingTypeName;
	}

	public void setBindingTypeName(String bindingTypeName) {
		this.bindingTypeName = bindingTypeName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bindingtype")
	public Set<Items> getItemses() {
		return this.itemses;
	}

	public void setItemses(Set<Items> itemses) {
		this.itemses = itemses;
	}

}
