package com.rasik.model;

// Generated Jan 20, 2014 10:30:33 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category", catalog = "rasiknew")
public class Category implements java.io.Serializable {

	private Integer categoryId;
	private String categoryHeadEnglish;
	private String categoryHeadMarathi;
	private Set<Itemscategory> itemscategories = new HashSet<Itemscategory>(0);

	public Category() {
	}

	public Category(String categoryHeadEnglish, String categoryHeadMarathi,
			Set<Itemscategory> itemscategories) {
		this.categoryHeadEnglish = categoryHeadEnglish;
		this.categoryHeadMarathi = categoryHeadMarathi;
		this.itemscategories = itemscategories;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CategoryId", unique = true, nullable = false)
	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "CategoryHeadEnglish", length = 50)
	public String getCategoryHeadEnglish() {
		return this.categoryHeadEnglish;
	}

	public void setCategoryHeadEnglish(String categoryHeadEnglish) {
		this.categoryHeadEnglish = categoryHeadEnglish;
	}

	@Column(name = "CategoryHeadMarathi", length = 150)
	public String getCategoryHeadMarathi() {
		return this.categoryHeadMarathi;
	}

	public void setCategoryHeadMarathi(String categoryHeadMarathi) {
		this.categoryHeadMarathi = categoryHeadMarathi;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
	public Set<Itemscategory> getItemscategories() {
		return this.itemscategories;
	}

	public void setItemscategories(Set<Itemscategory> itemscategories) {
		this.itemscategories = itemscategories;
	}

}
