package com.rasik.model;

// Generated Jan 20, 2014 10:30:33 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Currency generated by hbm2java
 */
@Entity
@Table(name = "currency", catalog = "rasiknew")
public class Currency implements java.io.Serializable {

	private Integer currencyId;
	private String currencyName;
	private Double currencyRate;

	public Currency() {
	}

	public Currency(String currencyName, Double currencyRate) {
		this.currencyName = currencyName;
		this.currencyRate = currencyRate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CurrencyId", unique = true, nullable = false)
	public Integer getCurrencyId() {
		return this.currencyId;
	}

	public void setCurrencyId(Integer currencyId) {
		this.currencyId = currencyId;
	}

	@Column(name = "CurrencyName", length = 50)
	public String getCurrencyName() {
		return this.currencyName;
	}

	public void setCurrencyName(String currencyName) {
		this.currencyName = currencyName;
	}

	@Column(name = "CurrencyRate", precision = 22, scale = 0)
	public Double getCurrencyRate() {
		return this.currencyRate;
	}

	public void setCurrencyRate(Double currencyRate) {
		this.currencyRate = currencyRate;
	}

}
