package com.rasik.model;

// Generated Jan 20, 2014 10:30:33 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonBackReference;
import org.hibernate.annotations.NamedQueries;
import org.hibernate.annotations.NamedQuery;


/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", catalog = "rasiknew")
@NamedQueries({
@NamedQuery(name="findAllCustomers",query="from Customer "),
@NamedQuery(name="findCustomerByUserName",query="from Customer cust where cust.username = :username ")
})
public class Customer implements java.io.Serializable {

	private int customerId;
	private Customertype customertype;
	private String englishName;
	private String marathiName;
	private String address1;
	private String address2;
	private String address3;
	private String pincode;
	private String city;
	private String state;
	private String country;
	private String email;
	private String phone1;
	private String phone2;
	private String fax;
	private String mobile;
	private String contactPerson;
	private String companyName;
	private String designation;

	private String firstName;
	private String lastName;
	private String username;
	private String password;
	@JsonBackReference
	private Set<CustomerRoles> customerRoleses = new HashSet<CustomerRoles>(0);

	
	@JsonBackReference
	private Set<Items> items = new HashSet<Items>(
			0);


	public Customer() {
	}

	
	
		public Customer(int customerId) {
		this.customerId = customerId;
	}

	public Customer(int customerId, Customertype customertype,
			String englishName, String marathiName, String address1,
			String address2, String address3, String pincode, String city,String state,
			String country, String email, String phone1, String phone2,
			String fax, String mobile, String contactPerson, String companyName,
			String designation,
			String firstName,
			String lastName,
			String userName,
			String password,
			Set<Items> items) {
		this.customerId = customerId;
		this.customertype = customertype;
		this.englishName = englishName;
		this.marathiName = marathiName;
		this.address1 = address1;
		this.address2 = address2;
		this.address3 = address3;
		this.pincode = pincode;
		this.city = city;
		this.state = state;
		this.country = country;
		this.email = email;
		this.phone1 = phone1;
		this.phone2 = phone2;
		this.fax = fax;
		this.mobile = mobile;
		this.contactPerson = contactPerson;
		this.companyName=companyName;
		this.designation=designation;

		this.firstName=firstName;
		this.lastName=lastName;
		this.username=userName;
		this.password=password;

		this.items = items;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "CustomerId", unique = true, nullable = false)
	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	@JsonBackReference
	private Set<Items> itemsCreatedByCustomer = new HashSet<Items>(
			0);


	@ManyToMany(mappedBy = "itemCustomerslog")
	public Set<Items> getItemsCreatedByCustomer() {
		return itemsCreatedByCustomer;
	}

	public void setItemsCreatedByCustomer(Set<Items> itemsCreatedByCustomer) {
		this.itemsCreatedByCustomer = itemsCreatedByCustomer;
	}


	
	@ManyToOne(fetch = FetchType.EAGER,cascade=CascadeType.ALL)
	@JoinColumn(name = "customerTypeId")
	public Customertype getCustomertype() {
		return this.customertype;
	}

	public void setCustomertype(Customertype customertype) {
		this.customertype = customertype;
	}

	@Column(name = "EnglishName", length = 120)
	public String getEnglishName() {
		return this.englishName;
	}

	public void setEnglishName(String englishName) {
		this.englishName = englishName;
	}

	@Column(name = "MarathiName", length = 350)
	public String getMarathiName() {
		return this.marathiName;
	}

	public void setMarathiName(String marathiName) {
		this.marathiName = marathiName;
	}

	@Column(name = "Address1", length = 135)
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "Address2", length = 135)
	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Column(name = "Address3", length = 135)
	public String getAddress3() {
		return this.address3;
	}

	public void setAddress3(String address3) {
		this.address3 = address3;
	}

	@Column(name = "PINCode", length = 15)
	public String getPincode() {
		return this.pincode;
	}

	public void setPincode(String pincode) {
		this.pincode = pincode;
	}

	@Column(name = "City", length = 50)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "Country", length = 50)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "Email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Phone1", length = 15)
	public String getPhone1() {
		return this.phone1;
	}

	public void setPhone1(String phone1) {
		this.phone1 = phone1;
	}

	@Column(name = "Phone2", length = 15)
	public String getPhone2() {
		return this.phone2;
	}

	public void setPhone2(String phone2) {
		this.phone2 = phone2;
	}

	@Column(name = "Fax", length = 15)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "Mobile", length = 15)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "ContactPerson", length = 130)
	public String getContactPerson() {
		return this.contactPerson;
	}

	public void setContactPerson(String contactPerson) {
		this.contactPerson = contactPerson;
	}

	@ManyToMany(mappedBy = "customers")
	public Set<Items> getItems() {
		return this.items;
	}

	public void setItems(
			Set<Items> items) {
		this.items = items;
	}

	/**
	 * @return the state
	 */
	@Column(name = "state", length = 45)
	public String getState() {
		return state;
	}

	/**
	 * @param state the state to set
	 */
	public void setState(String state) {
		this.state = state;
	}



	/**
	 * @return the designation
	 */
	@Column(name = "designation", length = 145)
	public String getDesignation() {
		return designation;
	}



	/**
	 * @param designation the designation to set
	 */
	public void setDesignation(String designation) {
		this.designation = designation;
	}



	/**
	 * @return the companyName
	 */
	@Column(name = "companyName", length = 145)
	public String getCompanyName() {
		return companyName;
	}



	/**
	 * @param companyName the companyName to set
	 */
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}



	/**
	 * @return the firstName
	 */
	@Column(name = "firstName", length = 45)
	public String getFirstName() {
		return firstName;
	}



	/**
	 * @param firstName the firstName to set
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}



	/**
	 * @return the lastName
	 */
	@Column(name = "lastName", length = 45)
	public String getLastName() {
		return lastName;
	}



	/**
	 * @param lastName the lastName to set
	 */
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}



	/**
	 * @return the username
	 */
	@Column(name = "username", length = 45)
	public String getUsername() {
		return username;
	}



	/**
	 * @param username the username to set
	 */
	public void setUsername(String userName) {
		this.username = userName;
	}



	/**
	 * @return the password
	 */
	@Column(name = "password", length = 45)
	public String getPassword() {
		return password;
	}



	/**
	 * @param password the password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}



	/**
	 * @return the customerRoleses
	 */
	public Set<CustomerRoles> getCustomerRoleses() {
		return customerRoleses;
	}



	/**
	 * @param customerRoleses the customerRoleses to set
	 */
	public void setCustomerRoleses(Set<CustomerRoles> customerRoleses) {
		this.customerRoleses = customerRoleses;
	}

}
