package com.rasik.model;

// Generated Jan 20, 2014 10:30:33 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.NamedQuery;

/**
 * Discounts generated by hbm2java
 */
@Entity
@Table(name = "discounts", catalog = "rasiknew")
@NamedQuery(name="findAllDiscounts",query="from Discounts ")
public class Discounts implements java.io.Serializable {

	private Integer discountId;
	private String description;
	private Double discountPer;
	private Date discountEndDate;
	private Float maxSaleDiscountPercentage;
	private String purchaseDiscount;
	private Set<Items> itemses = new HashSet<Items>(0);

	public Discounts() {
	}

	public Discounts(String description, Double discountPer,
			Date discountEndDate, Float maxSaleDiscountPercentage,
			String purchaseDiscount, Set<Items> itemses) {
		this.description = description;
		this.discountPer = discountPer;
		this.discountEndDate = discountEndDate;
		this.maxSaleDiscountPercentage = maxSaleDiscountPercentage;
		this.purchaseDiscount = purchaseDiscount;
		this.itemses = itemses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "DiscountId", unique = true, nullable = false)
	public Integer getDiscountId() {
		return this.discountId;
	}

	public void setDiscountId(Integer discountId) {
		this.discountId = discountId;
	}

	@Column(name = "Description", length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "DiscountPer", precision = 22, scale = 0)
	public Double getDiscountPer() {
		return this.discountPer;
	}

	public void setDiscountPer(Double discountPer) {
		this.discountPer = discountPer;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DiscountEndDate", length = 19)
	public Date getDiscountEndDate() {
		return this.discountEndDate;
	}

	public void setDiscountEndDate(Date discountEndDate) {
		this.discountEndDate = discountEndDate;
	}

	@Column(name = "MaxSaleDiscountPercentage", precision = 12, scale = 0)
	public Float getMaxSaleDiscountPercentage() {
		return this.maxSaleDiscountPercentage;
	}

	public void setMaxSaleDiscountPercentage(Float maxSaleDiscountPercentage) {
		this.maxSaleDiscountPercentage = maxSaleDiscountPercentage;
	}

	@Column(name = "PurchaseDiscount", length = 45)
	public String getPurchaseDiscount() {
		return this.purchaseDiscount;
	}

	public void setPurchaseDiscount(String purchaseDiscount) {
		this.purchaseDiscount = purchaseDiscount;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "discounts")
	public Set<Items> getItemses() {
		return this.itemses;
	}

	public void setItemses(Set<Items> itemses) {
		this.itemses = itemses;
	}

}
