package com.rasik.model;
// default package
// Generated Mar 7, 2014 4:42:35 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonBackReference;
import org.hibernate.annotations.NamedQueries;
import org.hibernate.annotations.NamedQuery;

/**
 * Edition generated by hbm2java
 */
@Entity
@Table(name = "edition", catalog = "rasiknew")
@NamedQueries({
@NamedQuery(name="findEditionByName",query="from Edition it where it.edition = :edition"),
@NamedQuery(name="findAllEditions",query="from Edition ")
})

public class Edition implements java.io.Serializable {

	private int editionId;
	private Integer editionMonth;
	private Integer editionYear;
	private String edition;
	@JsonBackReference
	private Set<Items> items = new HashSet<Items>(
			0);

	/**
	 * @return the items
	 */
	@ManyToMany(fetch=FetchType.EAGER,mappedBy = "editions")
	public Set<Items> getItems() {
		return items;
	}

	/**
	 * @param items the items to set
	 */
	public void setItems(Set<Items> items) {
		this.items = items;
	}

	public Edition() {
	}

	public Edition(int editionId) {
		this.editionId = editionId;
	}

	public Edition(int editionId, Integer editionMonth, Integer editionYear) {
		this.editionId = editionId;
		this.editionMonth = editionMonth;
		this.editionYear = editionYear;
	}

	@Id
	@Column(name = "editionId", unique = true, nullable = false)
	public int getEditionId() {
		return this.editionId;
	}

	public void setEditionId(int editionId) {
		this.editionId = editionId;
	}

	@Column(name = "editionMonth")
	public Integer getEditionMonth() {
		return this.editionMonth;
	}

	public void setEditionMonth(Integer editionMonth) {
		this.editionMonth = editionMonth;
	}

	@Column(name = "editionYear")
	public Integer getEditionYear() {
		return this.editionYear;
	}

	public void setEditionYear(Integer editionYear) {
		this.editionYear = editionYear;
	}

	/**
	 * @return the edition
	 */
	@Column(name = "edition")
	public String getEdition() {
		return edition;
	}

	/**
	 * @param edition the edition to set
	 */
	public void setEdition(String edition) {
		this.edition = edition;
	}

}
