package com.rasik.model;

// Generated Jan 20, 2014 10:30:33 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Itemspublsuppl generated by hbm2java
 */
@Entity
@Table(name = "itemspublsuppl", catalog = "rasiknew")
public class Itemspublsuppl implements java.io.Serializable {

	private Integer itemspublsupplId;
	private Publsuppl publsuppl;
	private Items items;

	public Itemspublsuppl() {
	}

	public Itemspublsuppl(Publsuppl publsuppl, Items items) {
		this.publsuppl = publsuppl;
		this.items = items;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "itemspublsupplId", unique = true, nullable = false)
	public Integer getItemspublsupplId() {
		return this.itemspublsupplId;
	}

	public void setItemspublsupplId(Integer itemspublsupplId) {
		this.itemspublsupplId = itemspublsupplId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PubSupId", nullable = false)
	public Publsuppl getPublsuppl() {
		return this.publsuppl;
	}

	public void setPublsuppl(Publsuppl publsuppl) {
		this.publsuppl = publsuppl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "itemId", nullable = false)
	public Items getItems() {
		return this.items;
	}

	public void setItems(Items items) {
		this.items = items;
	}

}
