package com.rasik.model;

// Generated Jan 20, 2014 10:30:33 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Itemscustomerrating generated by hbm2java
 */
@Entity
@Table(name = "itemscustomerrating", catalog = "rasiknew")
public class Itemscustomerrating implements java.io.Serializable {

	private int iditemRatingId;
	private Customer customer;
	private Items items;
	private Integer itemRatingStarValue;
	private String itemRatingDescription;

	public Itemscustomerrating() {
	}

	public Itemscustomerrating(int iditemRatingId, Customer customer,
			Items items) {
		this.iditemRatingId = iditemRatingId;
		this.customer = customer;
		this.items = items;
	}

	public Itemscustomerrating(int iditemRatingId, Customer customer,
			Items items, Integer itemRatingStarValue,
			String itemRatingDescription) {
		this.iditemRatingId = iditemRatingId;
		this.customer = customer;
		this.items = items;
		this.itemRatingStarValue = itemRatingStarValue;
		this.itemRatingDescription = itemRatingDescription;
	}

	@Id
	@Column(name = "iditemRatingId", unique = true, nullable = false)
	public int getIditemRatingId() {
		return this.iditemRatingId;
	}

	public void setIditemRatingId(int iditemRatingId) {
		this.iditemRatingId = iditemRatingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CustomerId", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "itemId", nullable = false)
	public Items getItems() {
		return this.items;
	}

	public void setItems(Items items) {
		this.items = items;
	}

	@Column(name = "itemRatingStarValue")
	public Integer getItemRatingStarValue() {
		return this.itemRatingStarValue;
	}

	public void setItemRatingStarValue(Integer itemRatingStarValue) {
		this.itemRatingStarValue = itemRatingStarValue;
	}

	@Column(name = "itemRatingDescription", length = 1045)
	public String getItemRatingDescription() {
		return this.itemRatingDescription;
	}

	public void setItemRatingDescription(String itemRatingDescription) {
		this.itemRatingDescription = itemRatingDescription;
	}

}
