package com.rasik.model;

// Generated Jan 20, 2014 10:30:33 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.NamedQueries;
import org.hibernate.annotations.NamedQuery;

/**
 * Itemsedition generated by hbm2java
 */
@Entity
@Table(name = "itemsedition", catalog = "rasiknew")
@NamedQueries({
@NamedQuery(name="findAllItemseditions",query="from Itemsedition "),
@NamedQuery(name="findItemseditionsByDesc",query="from Itemsedition it where it.itemsedition = :itemsedition")
})
public class Itemsedition implements java.io.Serializable {

	private int itemsEditionid;
	private String itemsedition;
	private String itemseditiondesc;
	private Set<Items> itemses = new HashSet<Items>(0);

	public Itemsedition() {
	}

	public Itemsedition(int itemsEditionid) {
		this.itemsEditionid = itemsEditionid;
	}

	public Itemsedition(int itemsEditionid, String itemsedition,
			String itemseditiondesc, Set<Items> itemses) {
		this.itemsEditionid = itemsEditionid;
		this.itemsedition = itemsedition;
		this.itemseditiondesc = itemseditiondesc;
		this.itemses = itemses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "itemsEditionid", unique = true, nullable = false)
	public int getItemsEditionid() {
		return this.itemsEditionid;
	}

	public void setItemsEditionid(int itemsEditionid) {
		this.itemsEditionid = itemsEditionid;
	}

	@Column(name = "itemsedition", length = 45)
	public String getItemsedition() {
		return this.itemsedition;
	}

	public void setItemsedition(String itemsedition) {
		this.itemsedition = itemsedition;
	}

	@Column(name = "itemseditiondesc", length = 145)
	public String getItemseditiondesc() {
		return this.itemseditiondesc;
	}

	public void setItemseditiondesc(String itemseditiondesc) {
		this.itemseditiondesc = itemseditiondesc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "itemsedition")
	public Set<Items> getItemses() {
		return this.itemses;
	}

	public void setItemses(Set<Items> itemses) {
		this.itemses = itemses;
	}

}
