package com.rasik.model;

// Generated Jan 20, 2014 10:30:33 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Itemsauthors generated by hbm2java
 */
@Entity
@Table(name = "itemsauthors", catalog = "rasiknew")
public class Itemsauthors implements java.io.Serializable {

	private Integer itemAuthorId;
	private Authors authors;
	private Items items;

	public Itemsauthors() {
	}

	public Itemsauthors(Authors authors, Items items) {
		this.authors = authors;
		this.items = items;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "itemAuthorId", unique = true, nullable = false)
	public Integer getItemAuthorId() {
		return this.itemAuthorId;
	}

	public void setItemAuthorId(Integer itemAuthorId) {
		this.itemAuthorId = itemAuthorId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AuthorId", nullable = false)
	public Authors getAuthors() {
		return this.authors;
	}

	public void setAuthors(Authors authors) {
		this.authors = authors;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "itemId", nullable = false)
	public Items getItems() {
		return this.items;
	}

	public void setItems(Items items) {
		this.items = items;
	}

}
