package com.rasik.model;

// Generated Jan 20, 2014 10:30:33 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonBackReference;
import org.hibernate.annotations.NamedQueries;
import org.hibernate.annotations.NamedQuery;

/**
 * Itemlanguage generated by hbm2java
 */
@Entity
@Table(name = "itemlanguage", catalog = "rasiknew")
@NamedQueries({
@NamedQuery(name="findAllItemlanguages",query="from Itemlanguage "),
@NamedQuery(name="findLanguageByName",query="from Itemlanguage it where it.languageName = :languageName")
})
public class Itemlanguage implements java.io.Serializable {

	private Integer languageId;
	private String languageName;
	@JsonBackReference
	private Set<Items> itemses = new HashSet<Items>(0);

	public Itemlanguage() {
	}

	public Itemlanguage(String languageName, Set<Items> itemses) {
		this.languageName = languageName;
		this.itemses = itemses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "LanguageId", unique = true, nullable = false)
	public Integer getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(Integer languageId) {
		this.languageId = languageId;
	}

	@Column(name = "LanguageName", length = 50)
	public String getLanguageName() {
		return this.languageName;
	}

	public void setLanguageName(String languageName) {
		this.languageName = languageName;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "itemlanguage")
	public Set<Items> getItemses() {
		return this.itemses;
	}

	public void setItemses(Set<Items> itemses) {
		this.itemses = itemses;
	}

}
