package com.rasik.model;

// Generated Jan 20, 2014 10:30:33 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Items generated by hbm2java
 */
@Entity
@Table(name = "items", catalog = "rasiknew")
public class Items implements java.io.Serializable {

	private Integer itemId;
	private Bindingtype bindingtype;
	private Itemtype itemtype;
	private Discounts discounts;
	private Itemlanguage itemlanguage;
	private Itemsedition itemsedition;
	private String userBookCode;
	private String englishName;
	private String marathiName;
	private Integer publisherCode;
	private Double price;
	private Integer qtyInHand;
	private Integer minLevel;
	private Integer maxLevel;
	private Double maxSalePrice;
	private Byte publMonth;
	private Integer publYear;
	private String isbnno;
	private Integer noOfPages;
	private String description;
	private String itemCoverImage;
	private String ebookFile;
	private String audioBookFile;
	private String printStatus;
	private Date maxSalePriceEndDate;
	private Double maxOwDiscountPrecent;
	private Date maxOwDiscountEndDate;
	private Double maxInwDiscountPercent;
	private Date maxInwDiscountEndDate;
	private Set<Itemsstockcenter> itemsstockcenters = new HashSet<Itemsstockcenter>(
			0);
	private Set<Itemsauthors> itemsauthorses = new HashSet<Itemsauthors>(0);
	private Set<Itemspublsuppl> itemspublsuppls = new HashSet<Itemspublsuppl>(0);
	private Set<Itemscustomerrating> itemscustomerratings = new HashSet<Itemscustomerrating>(
			0);
	private Set<Translation> translations = new HashSet<Translation>(0);
	private Set<Itemscategory> itemscategories = new HashSet<Itemscategory>(0);
	private Set<Awarddetail> awarddetails = new HashSet<Awarddetail>(0);

	public Items() {
	}

	public Items(Bindingtype bindingtype, Itemtype itemtype,
			Discounts discounts, Itemlanguage itemlanguage,
			Itemsedition itemsedition, String userBookCode, String englishName,
			String marathiName, Integer publisherCode, Double price,
			Integer qtyInHand, Integer minLevel, Integer maxLevel,
			Double maxSalePrice, Byte publMonth, Integer publYear,
			String isbnno, Integer noOfPages, String description,
			String itemCoverImage, String ebookFile, String audioBookFile,
			String printStatus, Date maxSalePriceEndDate,
			Double maxOwDiscountPrecent, Date maxOwDiscountEndDate,
			Double maxInwDiscountPercent, Date maxInwDiscountEndDate,
			Set<Itemsstockcenter> itemsstockcenters,
			Set<Itemsauthors> itemsauthorses,
			Set<Itemspublsuppl> itemspublsuppls,
			Set<Itemscustomerrating> itemscustomerratings,
			Set<Translation> translations, Set<Itemscategory> itemscategories,
			Set<Awarddetail> awarddetails) {
		this.bindingtype = bindingtype;
		this.itemtype = itemtype;
		this.discounts = discounts;
		this.itemlanguage = itemlanguage;
		this.itemsedition = itemsedition;
		this.userBookCode = userBookCode;
		this.englishName = englishName;
		this.marathiName = marathiName;
		this.publisherCode = publisherCode;
		this.price = price;
		this.qtyInHand = qtyInHand;
		this.minLevel = minLevel;
		this.maxLevel = maxLevel;
		this.maxSalePrice = maxSalePrice;
		this.publMonth = publMonth;
		this.publYear = publYear;
		this.isbnno = isbnno;
		this.noOfPages = noOfPages;
		this.description = description;
		this.itemCoverImage = itemCoverImage;
		this.ebookFile = ebookFile;
		this.audioBookFile = audioBookFile;
		this.printStatus = printStatus;
		this.maxSalePriceEndDate = maxSalePriceEndDate;
		this.maxOwDiscountPrecent = maxOwDiscountPrecent;
		this.maxOwDiscountEndDate = maxOwDiscountEndDate;
		this.maxInwDiscountPercent = maxInwDiscountPercent;
		this.maxInwDiscountEndDate = maxInwDiscountEndDate;
		this.itemsstockcenters = itemsstockcenters;
		this.itemsauthorses = itemsauthorses;
		this.itemspublsuppls = itemspublsuppls;
		this.itemscustomerratings = itemscustomerratings;
		this.translations = translations;
		this.itemscategories = itemscategories;
		this.awarddetails = awarddetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ItemId", unique = true, nullable = false)
	public Integer getItemId() {
		return this.itemId;
	}

	public void setItemId(Integer itemId) {
		this.itemId = itemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BindingTypeId")
	public Bindingtype getBindingtype() {
		return this.bindingtype;
	}

	public void setBindingtype(Bindingtype bindingtype) {
		this.bindingtype = bindingtype;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ItemTypeId")
	public Itemtype getItemtype() {
		return this.itemtype;
	}

	public void setItemtype(Itemtype itemtype) {
		this.itemtype = itemtype;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DiscountId")
	public Discounts getDiscounts() {
		return this.discounts;
	}

	public void setDiscounts(Discounts discounts) {
		this.discounts = discounts;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LanguageId")
	public Itemlanguage getItemlanguage() {
		return this.itemlanguage;
	}

	public void setItemlanguage(Itemlanguage itemlanguage) {
		this.itemlanguage = itemlanguage;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "itemseditionId")
	public Itemsedition getItemsedition() {
		return this.itemsedition;
	}

	public void setItemsedition(Itemsedition itemsedition) {
		this.itemsedition = itemsedition;
	}

	@Column(name = "UserBookCode", length = 15)
	public String getUserBookCode() {
		return this.userBookCode;
	}

	public void setUserBookCode(String userBookCode) {
		this.userBookCode = userBookCode;
	}

	@Column(name = "EnglishName", length = 120)
	public String getEnglishName() {
		return this.englishName;
	}

	public void setEnglishName(String englishName) {
		this.englishName = englishName;
	}

	@Column(name = "MarathiName", length = 350)
	public String getMarathiName() {
		return this.marathiName;
	}

	public void setMarathiName(String marathiName) {
		this.marathiName = marathiName;
	}

	@Column(name = "PublisherCode")
	public Integer getPublisherCode() {
		return this.publisherCode;
	}

	public void setPublisherCode(Integer publisherCode) {
		this.publisherCode = publisherCode;
	}

	@Column(name = "Price", precision = 22, scale = 0)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Column(name = "QtyInHand")
	public Integer getQtyInHand() {
		return this.qtyInHand;
	}

	public void setQtyInHand(Integer qtyInHand) {
		this.qtyInHand = qtyInHand;
	}

	@Column(name = "MinLevel")
	public Integer getMinLevel() {
		return this.minLevel;
	}

	public void setMinLevel(Integer minLevel) {
		this.minLevel = minLevel;
	}

	@Column(name = "MaxLevel")
	public Integer getMaxLevel() {
		return this.maxLevel;
	}

	public void setMaxLevel(Integer maxLevel) {
		this.maxLevel = maxLevel;
	}

	@Column(name = "MaxSalePrice", precision = 22, scale = 0)
	public Double getMaxSalePrice() {
		return this.maxSalePrice;
	}

	public void setMaxSalePrice(Double maxSalePrice) {
		this.maxSalePrice = maxSalePrice;
	}

	@Column(name = "PublMonth")
	public Byte getPublMonth() {
		return this.publMonth;
	}

	public void setPublMonth(Byte publMonth) {
		this.publMonth = publMonth;
	}

	@Column(name = "PublYear")
	public Integer getPublYear() {
		return this.publYear;
	}

	public void setPublYear(Integer publYear) {
		this.publYear = publYear;
	}

	@Column(name = "ISBNNo", length = 13)
	public String getIsbnno() {
		return this.isbnno;
	}

	public void setIsbnno(String isbnno) {
		this.isbnno = isbnno;
	}

	@Column(name = "NoOfPages")
	public Integer getNoOfPages() {
		return this.noOfPages;
	}

	public void setNoOfPages(Integer noOfPages) {
		this.noOfPages = noOfPages;
	}

	@Column(name = "Description", length = 1245)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "ItemCoverImage", length = 145)
	public String getItemCoverImage() {
		return this.itemCoverImage;
	}

	public void setItemCoverImage(String itemCoverImage) {
		this.itemCoverImage = itemCoverImage;
	}

	@Column(name = "EbookFile", length = 145)
	public String getEbookFile() {
		return this.ebookFile;
	}

	public void setEbookFile(String ebookFile) {
		this.ebookFile = ebookFile;
	}

	@Column(name = "AudioBookFile", length = 145)
	public String getAudioBookFile() {
		return this.audioBookFile;
	}

	public void setAudioBookFile(String audioBookFile) {
		this.audioBookFile = audioBookFile;
	}

	@Column(name = "printStatus", length = 45)
	public String getPrintStatus() {
		return this.printStatus;
	}

	public void setPrintStatus(String printStatus) {
		this.printStatus = printStatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MaxSalePriceEndDate", length = 10)
	public Date getMaxSalePriceEndDate() {
		return this.maxSalePriceEndDate;
	}

	public void setMaxSalePriceEndDate(Date maxSalePriceEndDate) {
		this.maxSalePriceEndDate = maxSalePriceEndDate;
	}

	@Column(name = "MaxOwDiscountPrecent", precision = 22, scale = 0)
	public Double getMaxOwDiscountPrecent() {
		return this.maxOwDiscountPrecent;
	}

	public void setMaxOwDiscountPrecent(Double maxOwDiscountPrecent) {
		this.maxOwDiscountPrecent = maxOwDiscountPrecent;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MaxOwDiscountEndDate", length = 10)
	public Date getMaxOwDiscountEndDate() {
		return this.maxOwDiscountEndDate;
	}

	public void setMaxOwDiscountEndDate(Date maxOwDiscountEndDate) {
		this.maxOwDiscountEndDate = maxOwDiscountEndDate;
	}

	@Column(name = "MaxInwDiscountPercent", precision = 22, scale = 0)
	public Double getMaxInwDiscountPercent() {
		return this.maxInwDiscountPercent;
	}

	public void setMaxInwDiscountPercent(Double maxInwDiscountPercent) {
		this.maxInwDiscountPercent = maxInwDiscountPercent;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MaxInwDiscountEndDate", length = 10)
	public Date getMaxInwDiscountEndDate() {
		return this.maxInwDiscountEndDate;
	}

	public void setMaxInwDiscountEndDate(Date maxInwDiscountEndDate) {
		this.maxInwDiscountEndDate = maxInwDiscountEndDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "items")
	public Set<Itemsstockcenter> getItemsstockcenters() {
		return this.itemsstockcenters;
	}

	public void setItemsstockcenters(Set<Itemsstockcenter> itemsstockcenters) {
		this.itemsstockcenters = itemsstockcenters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "items")
	public Set<Itemsauthors> getItemsauthorses() {
		return this.itemsauthorses;
	}

	public void setItemsauthorses(Set<Itemsauthors> itemsauthorses) {
		this.itemsauthorses = itemsauthorses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "items")
	public Set<Itemspublsuppl> getItemspublsuppls() {
		return this.itemspublsuppls;
	}

	public void setItemspublsuppls(Set<Itemspublsuppl> itemspublsuppls) {
		this.itemspublsuppls = itemspublsuppls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "items")
	public Set<Itemscustomerrating> getItemscustomerratings() {
		return this.itemscustomerratings;
	}

	public void setItemscustomerratings(
			Set<Itemscustomerrating> itemscustomerratings) {
		this.itemscustomerratings = itemscustomerratings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "items")
	public Set<Translation> getTranslations() {
		return this.translations;
	}

	public void setTranslations(Set<Translation> translations) {
		this.translations = translations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "items")
	public Set<Itemscategory> getItemscategories() {
		return this.itemscategories;
	}

	public void setItemscategories(Set<Itemscategory> itemscategories) {
		this.itemscategories = itemscategories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "items")
	public Set<Awarddetail> getAwarddetails() {
		return this.awarddetails;
	}

	public void setAwarddetails(Set<Awarddetail> awarddetails) {
		this.awarddetails = awarddetails;
	}

}
