package com.rasik.model;

// Generated Jan 20, 2014 10:30:33 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Publsuppl generated by hbm2java
 */
@Entity
@Table(name = "publsuppl", catalog = "rasiknew")
public class Publsuppl implements java.io.Serializable {

	private int pubSupId;
	private String englishName;
	private String marathiName;
	private String address1;
	private String address2;
	private String address3;
	private String pincode;
	private String city;
	private String country;
	private String email;
	private String phone1;
	private String phone2;
	private String fax;
	private String mobile;
	private String website;
	private String contactPerson;
	private Set<Itemspublsuppl> itemspublsuppls = new HashSet<Itemspublsuppl>(0);

	public Publsuppl() {
	}

	public Publsuppl(int pubSupId) {
		this.pubSupId = pubSupId;
	}

	public Publsuppl(int pubSupId, String englishName, String marathiName,
			String address1, String address2, String address3, String pincode,
			String city, String country, String email, String phone1,
			String phone2, String fax, String mobile, String website,
			String contactPerson, Set<Itemspublsuppl> itemspublsuppls) {
		this.pubSupId = pubSupId;
		this.englishName = englishName;
		this.marathiName = marathiName;
		this.address1 = address1;
		this.address2 = address2;
		this.address3 = address3;
		this.pincode = pincode;
		this.city = city;
		this.country = country;
		this.email = email;
		this.phone1 = phone1;
		this.phone2 = phone2;
		this.fax = fax;
		this.mobile = mobile;
		this.website = website;
		this.contactPerson = contactPerson;
		this.itemspublsuppls = itemspublsuppls;
	}

	@Id
	@Column(name = "PubSupId", unique = true, nullable = false)
	public int getPubSupId() {
		return this.pubSupId;
	}

	public void setPubSupId(int pubSupId) {
		this.pubSupId = pubSupId;
	}

	@Column(name = "EnglishName", length = 120)
	public String getEnglishName() {
		return this.englishName;
	}

	public void setEnglishName(String englishName) {
		this.englishName = englishName;
	}

	@Column(name = "MarathiName", length = 350)
	public String getMarathiName() {
		return this.marathiName;
	}

	public void setMarathiName(String marathiName) {
		this.marathiName = marathiName;
	}

	@Column(name = "Address1", length = 135)
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "Address2", length = 135)
	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Column(name = "Address3", length = 135)
	public String getAddress3() {
		return this.address3;
	}

	public void setAddress3(String address3) {
		this.address3 = address3;
	}

	@Column(name = "PINCode", length = 15)
	public String getPincode() {
		return this.pincode;
	}

	public void setPincode(String pincode) {
		this.pincode = pincode;
	}

	@Column(name = "City", length = 50)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "Country", length = 50)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "Email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Phone1", length = 15)
	public String getPhone1() {
		return this.phone1;
	}

	public void setPhone1(String phone1) {
		this.phone1 = phone1;
	}

	@Column(name = "Phone2", length = 15)
	public String getPhone2() {
		return this.phone2;
	}

	public void setPhone2(String phone2) {
		this.phone2 = phone2;
	}

	@Column(name = "Fax", length = 15)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "Mobile", length = 15)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "Website", length = 115)
	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	@Column(name = "ContactPerson", length = 130)
	public String getContactPerson() {
		return this.contactPerson;
	}

	public void setContactPerson(String contactPerson) {
		this.contactPerson = contactPerson;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "publsuppl")
	public Set<Itemspublsuppl> getItemspublsuppls() {
		return this.itemspublsuppls;
	}

	public void setItemspublsuppls(Set<Itemspublsuppl> itemspublsuppls) {
		this.itemspublsuppls = itemspublsuppls;
	}

}
