package com.rasik.model;
// default package
// Generated Mar 7, 2014 4:42:35 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonBackReference;

/**
 * reprint generated by hbm2java
 */
@Entity
@Table(name = "reprint", catalog = "rasiknew")
public class Reprint implements java.io.Serializable {

	private int reprintId;
	private Integer reprintMonth;
	private Integer reprintYear;
	@JsonBackReference
	private Set<Items> items = new HashSet<Items>(
			0);

	/**
	 * @return the items
	 */
	@ManyToMany(fetch=FetchType.EAGER,mappedBy = "reprints")
	public Set<Items> getItems() {
		return items;
	}

	/**
	 * @param items the items to set
	 */
	public void setItems(Set<Items> items) {
		this.items = items;
	}

	public Reprint() {
	}

	public Reprint(int reprintId) {
		this.reprintId = reprintId;
	}

	public Reprint(int reprintId, Integer reprintMonth, Integer reprintYear) {
		this.reprintId = reprintId;
		this.reprintMonth = reprintMonth;
		this.reprintYear = reprintYear;
	}

	@Id
	@Column(name = "reprintId", unique = true, nullable = false)
	public int getReprintId() {
		return this.reprintId;
	}

	public void setReprintId(int reprintId) {
		this.reprintId = reprintId;
	}

	@Column(name = "reprintMonth")
	public Integer getReprintMonth() {
		return this.reprintMonth;
	}

	public void setReprintMonth(Integer reprintMonth) {
		this.reprintMonth = reprintMonth;
	}

	@Column(name = "reprintYear")
	public Integer getReprintYear() {
		return this.reprintYear;
	}

	public void setReprintYear(Integer reprintYear) {
		this.reprintYear = reprintYear;
	}

}
