package com.rasik.model;

// Generated Jan 20, 2014 10:30:33 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.NamedQueries;
import org.hibernate.annotations.NamedQuery;

/**
 * Translation generated by hbm2java
 */
@Entity
@Table(name = "translation", catalog = "rasiknew")
@NamedQueries({
@NamedQuery(name="findAllTranslations",query="from Translation "),
@NamedQuery(name="findTranslationByName",query="from Translation it where it.originalname = :originalname")
})

public class Translation implements java.io.Serializable {

	private int translationId;
	private Items items;
	private String translatedfrom;
	private String originalname;
	private String originalauthor;

	public Translation() {
	}

	public Translation(int translationId) {
		this.translationId = translationId;
	}

	public Translation(int translationId, Items items, String translatedfrom,
			String originalname, String originalauthor) {
		this.translationId = translationId;
		this.items = items;
		this.translatedfrom = translatedfrom;
		this.originalname = originalname;
		this.originalauthor = originalauthor;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "translationId", unique = true, nullable = false)
	public int getTranslationId() {
		return this.translationId;
	}

	public void setTranslationId(int translationId) {
		this.translationId = translationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "itemsId")
	public Items getItems() {
		return this.items;
	}

	public void setItems(Items items) {
		this.items = items;
	}

	@Column(name = "translatedfrom", length = 45)
	public String getTranslatedfrom() {
		return this.translatedfrom;
	}

	public void setTranslatedfrom(String translatedfrom) {
		this.translatedfrom = translatedfrom;
	}

	@Column(name = "originalname", length = 45)
	public String getOriginalname() {
		return this.originalname;
	}

	public void setOriginalname(String originalname) {
		this.originalname = originalname;
	}

	@Column(name = "originalauthor", length = 85)
	public String getOriginalauthor() {
		return this.originalauthor;
	}

	public void setOriginalauthor(String originalauthor) {
		this.originalauthor = originalauthor;
	}

}
